### ISSUE TITLE
Request not an Issue! Please help

### ISSUE THREAD

**Issue by Neney22** [jaimeMF/youtube-dl-web#10]
Hi, this project is great! it would be really nice if you show us how would you present the results in a different page from the downloader. for example when i click get file, it sends me to a different page showing the download link and etc.. instead of showing it at the bottom of the page

**Comment by jaimeMF** [comment]
Currently it's a [single page](https://github.com/jaimeMF/youtube-dl-web/blob/1d93f5524506e61b950009bbdd3c245f4df2bbf5/index.html) that uses javascript for fetching the video info. I think that for what you want to do, you would need to run a script on the server (e.g: PHP, Ruby, Python ....).

**Comment by Neney22** [comment]
Thank you for that information and also one more thing. Is there any way of changing the size or make a resizable Table, when the output is given. I want to find a way on how to change the sizes of the download, title, format etc..

**Comment by Neney22** [comment]
*I found a way of changing the width of each cell independently, but i wish it did it automatically specially the letters are moving down instead of left to right.
