### ISSUE TITLE
Videos from Vine are not downloading.

### ISSUE THREAD

**Issue by Neney22** [jaimeMF/youtube-dl-web#12]
Hello, the videos from vine.co are not working with your code but it downloads with youtube-dl in terminal. heres an example of the videos, i tried different ones already. https://vine.co/v/5zDDlpmiQJW.
Others websites work pretty good . I am using the youtube-dl api server from you, I created my own server on herokuapp.com

**Comment by jaimeMF** [comment]
You have to upgrade youtube-dl (2016.07.02  or higher is needed).

**Comment by Neney22** [comment]
I have updated youtube-dl to the last version on my server but i have no idea how to update youtube-dl on youtube-dl-api  app using heroku

**Comment by jaimeMF** [comment]
``` bash
$ heroku plugins:install https://github.com/heroku/heroku-repo.git
$ heroku repo:reset
$ git push heroku master
```

**Comment by Neney22** [comment]
Im getting 


  !    `repo:reset` is not a heroku command.
 !    Perhaps you meant `pg:reset`.
 !    See `heroku help` for a list of available 

After I use `$ heroku repo:reset`

**Comment by jaimeMF** [comment]
Have you actually run `heroku plugins:install https://github.com/heroku/heroku-repo.git`?

**Comment by Neney22** [comment]
Yes i did this is my output

> Installing https://github.com/heroku/heroku-repo.git... User-MBP:youtube-dl-api-server User$

**Comment by jaimeMF** [comment]
Whats the output of `heroku plugins`?

**Comment by Neney22** [comment]
Thats all It gives me after I run`heroku plugins:install https://github.com/heroku/heroku-repo.git`

This:
Installing https://github.com/heroku/heroku-repo.git... User-MBP:youtube-dl-api-server User$

**Comment by Neney22** [comment]
If i do `heroku plugins`
I get 

> You have no installed plugins.

**Comment by jaimeMF** [comment]
If the plugin fails to install, I can't help you. I guess you should ask heroku.

**Comment by jaimeMF** [comment]
Sorry, try with `heroku plugins:install heroku-repo` instead.

**Comment by Neney22** [comment]
Yes I just did and it worked, but now when I run `git push heroku master` it gives me another error

> fatal: Not a git repository (or any of the parent directories): .git

Sorry for bothering so much

**Comment by jaimeMF** [comment]
>  fatal: Not a git repository (or any of the parent directories): .git

You have to run the command from the `youtube-dl-api-server` directory.

**Comment by Neney22** [comment]
Done!  When I checked the 

> youtube-dl 

 version  inside the `youtube-dl-api-server` 
it returns version 2016.06.25
But when I try to use the  `pip install  --upgrade --user youtube-dl` from the youtube-dl-api-server directory I receive 

> pip: command not found

**Comment by jaimeMF** [comment]
I don't know your setup, but it's not really relevant because `youtube-dl` is automatically installed on heroku's servers.

**Comment by Neney22** [comment]
I got it, i simply had to do `youtube-dl -U`  inside the `youtube-dl-api-server`  directory to update youtube-dl to the latest version but, the Vine videos are still not working though

**Comment by jaimeMF** [comment]
Check you have 2016.07.02 or higher.

**Comment by Neney22** [comment]
I do
this is my code when i run this command 

> user-MBP:youtube-dl-api-server User$ youtube-dl --version

I get 
`2016.07.03.1`

**Comment by jaimeMF** [comment]
It works for me with the URL you posted, does it fail locally or on heroku?

**Comment by Neney22** [comment]
> user-MBP:youtube-dl-api-server User$ youtube-dl https://vine.co/v/5zDDlpmiQJW
> [Vine] 5zDDlpmiQJW: Downloading webpage
> [download] Destination: Spider-man VS Captain America freestyle rap battle. 🔥🔥😳😳-5zDDlpmiQJW.mp4
> [download] 100% of 2.48MiB in 00:00

Im guessing is on heroku? because on my website it doesn't but when i download it through terminal it downloads

**Comment by jaimeMF** [comment]
Run `heroku repo:purge_cache` before `heroku repo:reset`.

**Comment by Neney22** [comment]
Thanks! You a master :) Finally I got it to work
