### ISSUE TITLE
youtube broken

### ISSUE THREAD

**Issue by rdp** [jaimeMF/youtube-dl-web#3]
does downloading https://www.youtube.com/watch?v=txTdcqDTL9E work for anybody?

**Comment by jaimeMF** [comment]
It works fine now, probably the problem is that the server was down (it got too many requests).

**Comment by rdp** [comment]
sweet works now [though doesn't display links for downloading all the various different resolutions, but I'm ok with that]

**Comment by jaimeMF** [comment]
I've opened a new issue for that: #4.
