### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by simetin** [jaimeMF/youtube-dl-web#5]
Hi, I am trying to install Youtube-dl-web, but I always get this error: 
Oops! Something went wrong. Make sure the website is supported by youtube-dl.
It's the same error that on your demo page: http://jaimemf.github.io/youtube-dl-web/. It seems to be an communication error with the Api. Is there anything broken ?

Thanks

**Comment by jaimeMF** [comment]
The server has got too many requests, If you setup your own server, you just need to change [this line](https://github.com/jaimeMF/youtube-dl-web/blob/gh-pages/VideoInfo.js#L5).

**Comment by NevDawg** [comment]
how do i setup my own youtube-dl-api-server ? i need a more detailed instruction i am running a vps plesk 12 centos 6.9. do i need to create a subdomain and host it on this?
