### ISSUE TITLE
Error: Server Error

### ISSUE THREAD

**Issue by paulwscom** [jaimeMF/youtube-dl-web#7]
Im experiencing server error with message 
"Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds."

i dont know what to do cause im only a beginner.

**Comment by jaimeMF** [comment]
It works with https://www.youtube.com/watch?v=36lSzUMBJnc, can you post the URL you are trying to download?

**Comment by paulwscom** [comment]
Not work
http://wapmon-proxy-s10.appspot.com/api/info?url=https://www.youtube.com/watch?v=36lSzUMBJnc

**Comment by jaimeMF** [comment]
This is a problem with [youtube-dl-api-server](https://github.com/jaimeMF/youtube-dl-api-server) not with youtube-dl-web. Note that on my AppEngine instance it works fine (https://youtube-dl.appspot.com/api/info?url=https://www.youtube.com/watch?v=36lSzUMBJnc), it must be something wrong on yours and you should check the error log.

**Comment by paulwscom** [comment]
How can i solve this? Sorry im only a beginner using appengine. Btw thanks for this codes, i appreciate it.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~wapmon-proxy-s10/0-2.389737492862595375/mainGAE.py", line 6, in <module>
    import youtube_dl
ImportError: No module named youtube_dl

**Comment by jaimeMF** [comment]
Make sure you follow the steps in https://youtube-dl-api-server.readthedocs.org/en/latest/install.html#app-engine and if doesn't work open a new issue in https://github.com/jaimeMF/youtube-dl-api-server.
