### ISSUE TITLE
Upgrade youtube-dl

### ISSUE THREAD

**Issue by fenollp** [jaimeMF/youtube-dl-web#8]
API says it uses `"youtube-dl.version": "2015.05.20"`.

Could you update your appspot to a later version?
This would help with fixing broken things

**Comment by jaimeMF** [comment]
Done. If you are using the API for your own application, please deploy [your own server](https://github.com/jaimeMF/youtube-dl-api-server).

**Comment by fenollp** [comment]
Thanks! Will do. It's just so that I can handily give out the link to friends and they do the dl themselves. Nothing big :)
